{
 "title": "NetworkData",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "name1",
    "query": "SELECT name FROM networks WHERE number=1 LIMIT 1;"
   },
   {
    "name": "name0",
    "query": "SELECT name FROM networks WHERE number=0 LIMIT 1;"
   },
   {
    "name": "name2",
    "query": "SELECT name FROM networks WHERE number=2 LIMIT 1;"
   },
   {
    "name": "name3",
    "query": "SELECT name FROM networks WHERE number=3 LIMIT 1;"
   },
   {
    "name": "name4",
    "query": "SELECT name FROM networks WHERE number=4 LIMIT 1;"
   },
   {
    "name": "name5",
    "query": "SELECT name FROM networks WHERE number=5 LIMIT 1;"
   },
   {
    "name": "name6",
    "query": "SELECT name FROM networks WHERE number=6 LIMIT 1;"
   },
   {
    "name": "name7",
    "query": "SELECT name FROM networks WHERE number=7 LIMIT 1;"
   },
   {
    "name": "name8",
    "query": "SELECT name FROM networks WHERE number=8 LIMIT 1;"
   },
   {
    "name": "names",
    "query": "SELECT DISTINCT name FROM networks;"
   },
   {
    "name": "name9",
    "query": "SELECT name FROM networks WHERE number=9 LIMIT 1;"
   },
   {
    "name": "name10",
    "query": "SELECT name FROM networks WHERE number=10 LIMIT 1;"
   },
   {
    "name": "name11",
    "query": "SELECT name FROM networks WHERE number=11 LIMIT 1;"
   },
   {
    "name": "name12",
    "query": "SELECT name FROM networks WHERE number=12 LIMIT 1;"
   },
   {
    "name": "name13",
    "query": "SELECT name FROM networks WHERE number=13 LIMIT 1;"
   },
   {
    "name": "name14",
    "query": "SELECT name FROM networks WHERE number=14 LIMIT 1;"
   },
   {
    "name": "name15",
    "query": "SELECT name FROM networks WHERE number=15 LIMIT 1;"
   },
   {
    "name": "name16",
    "query": "SELECT name FROM networks WHERE number=16 LIMIT 1;"
   },
   {
    "name": "name17",
    "query": "SELECT name FROM networks WHERE number=17 LIMIT 1;"
   },
   {
    "name": "name18",
    "query": "SELECT name FROM networks WHERE number=18 LIMIT 1;"
   },
   {
    "name": "name19",
    "query": "SELECT name FROM networks WHERE number=19 LIMIT 1;"
   },
   {
    "name": "name20",
    "query": "SELECT name FROM networks WHERE number=20 LIMIT 1;"
   }
  ]
 },
 "panels": [
  {
   "title": "Total (Past two hours)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "queryText": "SELECT sent, recv, time FROM networks LIMIT 16;",
     "rawQueryText": "SELECT sent, recv, time FROM networks LIMIT 16;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "$name3",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "queryText": "SELECT sent, recv, time FROM networks WHERE number=3;",
     "rawQueryText": "SELECT sent, recv, time FROM networks WHERE number=3;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "$name2",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "queryText": "SELECT sent, recv, time FROM networks WHERE number=2;",
     "rawQueryText": "SELECT sent, recv, time FROM networks WHERE number=2;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "${names}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "queryText": "SELECT sent, recv, time FROM networks WHERE number=1;",
     "rawQueryText": "SELECT sent, recv, time FROM networks WHERE number=1;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "$name6",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "queryText": "SELECT sent, recv, time FROM networks WHERE number=6;",
     "rawQueryText": "SELECT sent, recv, time FROM networks WHERE number=6;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "$name7",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "queryText": "SELECT sent, recv, time FROM networks WHERE number=7;",
     "rawQueryText": "SELECT sent, recv, time FROM networks WHERE number=7;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "$name8",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "queryText": "SELECT sent, recv, time FROM networks WHERE number=8;",
     "rawQueryText": "SELECT sent, recv, time FROM networks WHERE number=8;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "$name0",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "queryText": "SELECT sent, recv, time FROM networks WHERE number=0;",
     "rawQueryText": "SELECT sent, recv, time FROM networks WHERE number=0;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "$name10",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "queryText": "SELECT sent, recv, time FROM networks WHERE number=10;",
     "rawQueryText": "SELECT sent, recv, time FROM networks WHERE number=10;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "$name11",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "queryText": "SELECT sent, recv, time FROM networks WHERE number=11;",
     "rawQueryText": "SELECT sent, recv, time FROM networks WHERE number=11;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "$name4",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "queryText": "SELECT sent, recv, time FROM networks WHERE number=4;",
     "rawQueryText": "SELECT sent, recv, time FROM networks WHERE number=4;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "$name13",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "queryText": "SELECT sent, recv, time FROM networks WHERE number=13;",
     "rawQueryText": "SELECT sent, recv, time FROM networks WHERE number=13;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "$name9",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "queryText": "SELECT sent, recv, time FROM networks WHERE number=9;",
     "rawQueryText": "SELECT sent, recv, time FROM networks WHERE number=9;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "$name15",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "queryText": "SELECT sent, recv, time FROM networks WHERE number=15;",
     "rawQueryText": "SELECT sent, recv, time FROM networks WHERE number=15;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "$name12",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "queryText": "SELECT sent, recv, time FROM networks WHERE number=12;",
     "rawQueryText": "SELECT sent, recv, time FROM networks WHERE number=12;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "$name17",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "queryText": "SELECT sent, recv, time FROM networks WHERE number=17;",
     "rawQueryText": "SELECT sent, recv, time FROM networks WHERE number=17;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "$name14",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "queryText": "SELECT sent, recv, time FROM networks WHERE number=14;",
     "rawQueryText": "SELECT sent, recv, time FROM networks WHERE number=14;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "$name16",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "queryText": "SELECT sent, recv, time FROM networks WHERE number=16;",
     "rawQueryText": "SELECT sent, recv, time FROM networks WHERE number=16;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}